spring:
  data:
    mongodb:
      uri: mongodb+srv://Changed username:password@cluster0.clmwmqy.mongodb.net/?appName=Cluster0
      database: PAULDB
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /Paul
